apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: sova
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
      nodePort: 30900
    - name: minio-console
      port: 9001
      targetPort: 9001
      nodePort: 30901
